keys:
  # Replace this after creating /var/lib/sops-nix/age/keys.txt.
  # Get it with:
  #   sudo grep 'public key:' /var/lib/sops-nix/age/keys.txt
  - &nixos_laptop_age age1uhxcp823f44hvnmdr4cm78ax8zl72gvuptrrhmz7m3rs8mk2t9gqe89v2f

  # YubiKey-backed GPG key.
  - &yubikey_gpg 955986AF6BFBECAF1605620C2F0C8012A924FBAA

creation_rules:
  - path_regex: ^secrets/.*\.yaml$
    key_groups:
      - age:
          - *nixos_laptop_age
        pgp:
          - *yubikey_gpg
